
package ttknpdev.exercise1;

import ttknpdev.frames.MyFrames;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class HelloWorld extends MyFrames implements ActionListener {
   // private  myFrames;
   /**
    * Creates new form HelloWorld
    */
   public HelloWorld(String title) {
      super(title);
      // myFrames = new MyFrames("test helloworld ");
      initComponents();
      // initComponents();
   }

   /**
    * This method is called from within the constructor to
    * initialize the form. WARNING: Do NOT modify this code.
    * The content of this method is always regenerated by
    * the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabelName = new javax.swing.JLabel();
      jTextFieldName = new javax.swing.JTextField();
      jButtonName = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabelName.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
      jLabelName.setText("What's your name ?");

      jTextFieldName.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N

      jButtonName.setFont(new java.awt.Font("sansserif", 1, 21)); // NOI18N
      jButtonName.setText("send");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(29, 29, 29)
            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(156, Short.MAX_VALUE)
            .addComponent(jButtonName)
            .addGap(158, 158, 158))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(45, 45, 45)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabelName)
               .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(31, 31, 31)
            .addComponent(jButtonName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(24, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
      /* Create and display the form */
      HelloWorld helloWorld = new HelloWorld("test helloworld ui");
      java.awt.EventQueue.invokeLater(() -> {
         helloWorld.setVisible(true);
         helloWorld.jButtonName.addActionListener(helloWorld);
         // helloWorld.jButtonName.addActionListener(helloWorld);
      });
   }
   
    @Override
    public void actionPerformed(ActionEvent e) {
       // System.out.println(e.getActionCommand()); // return send
       int confirm = JOptionPane.showConfirmDialog(this, "Are you "+jTextFieldName.getText()+" Right?");
      switch (confirm) {
         case JOptionPane.YES_OPTION:
            System.out.println("takes YES!");
            break;
         case JOptionPane.NO_OPTION:
            System.out.println("takes NO!");
            break;
         default:
            System.out.println("takes Cancel!");
            break;
      }
       jTextFieldName.setText("");
    }
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonName;
   private javax.swing.JLabel jLabelName;
   private javax.swing.JTextField jTextFieldName;
   // End of variables declaration//GEN-END:variables
}
