package ttknpdev.exercise2;

import ttknpdev.frames.MyFrames;
import java.awt.EventQueue;
import ttknpdev.log.MyLog;

public class ConvertCelsius extends MyFrames implements Runnable {

   /**
    * Creates new form ConvertCelsius
    */
   public ConvertCelsius(String title) {
      super(title);
      MyLog.convertCelSius.info("initialized components");
      initComponents(); // need to create object this class  
   }

   /**
    * This method is called from within the constructor to
    * initialize the form. WARNING: Do NOT modify this code.
    * The content of this method is always regenerated by
    * the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanelConvert = new javax.swing.JPanel();
      jLabelTitle = new javax.swing.JLabel();
      jTextFieldCelsius = new javax.swing.JTextField();
      jButtonConvert = new javax.swing.JButton();
      jLabelResult = new javax.swing.JLabel();
      jLabelUnitCel = new javax.swing.JLabel();
      jLabelUnitFah = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabelTitle.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
      jLabelTitle.setText("Convert celsius to fahrenheit");
      jLabelTitle.setMaximumSize(new java.awt.Dimension(256, 16));
      jLabelTitle.setMinimumSize(new java.awt.Dimension(256, 16));

      jTextFieldCelsius.setFont(new java.awt.Font("sansserif", 1, 25)); // NOI18N
      jTextFieldCelsius.setHorizontalAlignment(javax.swing.JTextField.CENTER);

      jButtonConvert.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
      jButtonConvert.setText("convert");

      jLabelResult.setFont(new java.awt.Font("sansserif", 1, 25)); // NOI18N
      jLabelResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

      jLabelUnitCel.setFont(new java.awt.Font("sansserif", 0, 32)); // NOI18N
      jLabelUnitCel.setText("°C");

      jLabelUnitFah.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
      jLabelUnitFah.setText("°F");

      javax.swing.GroupLayout jPanelConvertLayout = new javax.swing.GroupLayout(jPanelConvert);
      jPanelConvert.setLayout(jPanelConvertLayout);
      jPanelConvertLayout.setHorizontalGroup(
         jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanelConvertLayout.createSequentialGroup()
            .addGroup(jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanelConvertLayout.createSequentialGroup()
                     .addGap(71, 71, 71)
                     .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(jPanelConvertLayout.createSequentialGroup()
                     .addGap(136, 136, 136)
                     .addComponent(jButtonConvert))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConvertLayout.createSequentialGroup()
                     .addGap(105, 105, 105)
                     .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(18, 18, 18)
                     .addComponent(jLabelUnitFah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(31, 31, 31)))
               .addGroup(jPanelConvertLayout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jTextFieldCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(jLabelUnitCel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(64, Short.MAX_VALUE))
      );
      jPanelConvertLayout.setVerticalGroup(
         jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanelConvertLayout.createSequentialGroup()
            .addGap(48, 48, 48)
            .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jTextFieldCelsius)
               .addComponent(jLabelUnitCel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
            .addGroup(jPanelConvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabelUnitFah, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(56, 56, 56)
            .addComponent(jButtonConvert)
            .addGap(61, 61, 61))
      );

      jLabelTitle.getAccessibleContext().setAccessibleName("jLabelTitle");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanelConvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanelConvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(ConvertCelsius.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(ConvertCelsius.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(ConvertCelsius.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(ConvertCelsius.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      /* Create and display the form */
      new ConvertCelsius("convert celsius").display();
   }
   public void display() {
       EventQueue.invokeLater(this);
   }

   @Override
   public void run() {
       // do something after run  
       this.jButtonConvert.addActionListener((event) -> {
          // (°C x 9/5) + 32 =°F
          Float celsius = Float.valueOf(jTextFieldCelsius.getText());
          // Float fah = (float)(celsius*1.80)+32;
          jLabelResult.setText( String.valueOf(((celsius*1.80)+32)) );
       });
   }
   
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonConvert;
   private javax.swing.JLabel jLabelResult;
   private javax.swing.JLabel jLabelTitle;
   private javax.swing.JLabel jLabelUnitCel;
   private javax.swing.JLabel jLabelUnitFah;
   private javax.swing.JPanel jPanelConvert;
   private javax.swing.JTextField jTextFieldCelsius;
   // End of variables declaration//GEN-END:variables
}
