
package ttknpdev.understandgui;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import ttknpdev.frames.MyFrames;

public class SecondGUISwing extends javax.swing.JPanel {


   public SecondGUISwing() {
      // don't set panel in this construcrtor
      initComponents();
      // display();
   }

   /**
    * This method is called from within the constructor to
    * initialize the form. WARNING: Do NOT modify this code.
    * The content of this method is always regenerated by
    * the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabelTitleDistance = new javax.swing.JLabel();
      jTextFieldKilometers = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabelTitleResult = new javax.swing.JLabel();
      jLabelResult = new javax.swing.JLabel();
      jButtonReset = new javax.swing.JButton();
      jRadioButtonInches = new javax.swing.JRadioButton();
      jRadioButtonMlies = new javax.swing.JRadioButton();
      jRadioButtonFeets = new javax.swing.JRadioButton();

      jLabelTitleDistance.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
      jLabelTitleDistance.setText("Put on your distance (Km.)");

      jTextFieldKilometers.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
      jTextFieldKilometers.setText("0.00");
      jTextFieldKilometers.setToolTipText("");
      jTextFieldKilometers.setActionCommand("<Not Set>");
      jTextFieldKilometers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

      jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
      jLabel1.setText("Kilometers.");

      jLabelTitleResult.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
      jLabelTitleResult.setText("The convert result is");

      jLabelResult.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
      jLabelResult.setText("...");

      jButtonReset.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
      jButtonReset.setText("reset");

      jRadioButtonInches.setText("inches");

      jRadioButtonMlies.setText("mlies");

      jRadioButtonFeets.setText("feets");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                     .addComponent(jLabelTitleDistance)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(jTextFieldKilometers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                     .addComponent(jLabel1))
                  .addGroup(layout.createSequentialGroup()
                     .addComponent(jLabelTitleResult)
                     .addGap(46, 46, 46)
                     .addComponent(jLabelResult))
                  .addGroup(layout.createSequentialGroup()
                     .addComponent(jRadioButtonInches)
                     .addGap(45, 45, 45)
                     .addComponent(jRadioButtonMlies)
                     .addGap(45, 45, 45)
                     .addComponent(jRadioButtonFeets))))
            .addContainerGap(18, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(80, 80, 80)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabelTitleDistance)
                  .addComponent(jTextFieldKilometers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(29, 29, 29)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jRadioButtonInches)
               .addComponent(jRadioButtonMlies)
               .addComponent(jRadioButtonFeets))
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabelTitleResult)
               .addComponent(jLabelResult))
            .addGap(53, 53, 53)
            .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(19, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonReset;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabelResult;
   private javax.swing.JLabel jLabelTitleDistance;
   private javax.swing.JLabel jLabelTitleResult;
   private javax.swing.JRadioButton jRadioButtonFeets;
   private javax.swing.JRadioButton jRadioButtonInches;
   private javax.swing.JRadioButton jRadioButtonMlies;
   private javax.swing.JTextField jTextFieldKilometers;
   // End of variables declaration//GEN-END:variables

   public void run() {

      SecondGUISwing secondGUISwing = new SecondGUISwing(); // this is panel 
      MyFrames myFrame = new MyFrames("testing");
      myFrame.setSize(545, 385);
      myFrame.setContentPane(secondGUISwing); // add panel

      // use btGroup for group any radiobuttons 
      ButtonGroup buttonGroup = new ButtonGroup();
      buttonGroup.add(secondGUISwing.jRadioButtonFeets);
      buttonGroup.add(secondGUISwing.jRadioButtonMlies);
      buttonGroup.add(secondGUISwing.jRadioButtonInches);

      secondGUISwing.display();
   }

   public void display() {

      // Float kilometers = Float.parseFloat(jTextFieldKilometers.getText());   
      // remember when user chose some radio
      // it will retrieve
      // some value on textfeild when user chose 
      jRadioButtonFeets.addItemListener(whenClicked -> {
         try {

            float kilometers = Float.parseFloat(jTextFieldKilometers.getText());
            jLabelResult.setText((kilometers * 3280.84) + "ft");

         } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Your input was correct!!", "warning", JOptionPane.WARNING_MESSAGE);
         }
      });

      jRadioButtonMlies.addItemListener(whenClicked -> {
         try {
            
            float kilometers = Float.parseFloat(jTextFieldKilometers.getText());
            jLabelResult.setText((kilometers * 0.6213711) + "mi");
         
         } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Your input was correct!!", "warning", JOptionPane.WARNING_MESSAGE);
         }
      });

      jRadioButtonInches.addItemListener(whenClicked -> {
         try {
            
            float kilometers = Float.parseFloat(jTextFieldKilometers.getText());
            jLabelResult.setText((kilometers * 39370.1) + "in");
         
         } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Your input was correct!!", "warning", JOptionPane.WARNING_MESSAGE);
         }
         float kilometers = Float.parseFloat(jTextFieldKilometers.getText());
         jLabelResult.setText((kilometers * 39370.1) + "in");
      });

      jButtonReset.addActionListener(whenClicked -> {
         jTextFieldKilometers.setText("");
      });

   }

}
